Repository operator-framework/operator-courier, pull requests merged in 2019-08, with the labels that each got.

#151 Filter out a black list of files from manifest bundle
  operatorcourier/manifest_parser.py
  operatorcourier/push.py
  tests/test_files/bundles/flatten/etcd_valid_input_7/0.9/image-references
  tests/test_files/bundles/flatten/etcd_valid_input_7_result/0.9/etcdbackup.crd.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_7_result/0.9/etcdcluster.crd.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_7_result/0.9/etcdoperator.clusterserviceversion.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_7_result/0.9/etcdrestore.crd.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_7_result/etcd.package.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_7_result/etcdoperator.clusterserviceversion.yaml
  tests/test_manifest_parser.py
Labels: lgtm, size/XL

#152 Increment version to v2.1.4
  setup.py
Labels: size/XS

#153 Include a randomized container folder in the tarred bundle
  operatorcourier/api.py
  operatorcourier/push.py
  tests/test_push.py
Labels: size/M

#154 Increment version to v2.1.5
  setup.py
Labels: size/XS

#155 Revisit Optional and Required Fields
  operatorcourier/const_io.py
Labels: lgtm, size/S

#156 Version bump to 2.1.6
  setup.py
Labels: size/XS

#157 Check optional keys exist before trying to access value
  operatorcourier/validate.py
Labels: lgtm, size/M
