Repository operator-framework/operator-courier, pull requests merged in 2019-03, with the labels that each got.

#32 Add MANIFEST.in and Makefile
  MANIFEST.in
  Makefile
  Pipfile
  Pipfile.lock
  docs/contributing.md
  setup.py
Labels: lgtm, size/L

#34 [docs] Add historical info and scripts
  docs/how-to-upload-artifact-deprecated.md
  scripts/get-quay-token
  scripts/push-to-quay
Labels: lgtm, size/L

#37 Fix error message for missing CSV
  operatorcourier/validate.py
Labels: lgtm, size/XS

#38 Expect ValueError to be raised
  tests/test_identify.py
Labels: lgtm, ok-to-test, size/XS

#35 Handle malformed yaml files
  operatorcourier/cli.py
  operatorcourier/identify.py
  tests/test_files/bundles/verification/nopkg.invalid.bundle.yaml
  tests/test_files/invalid.malformed.parser.error.yaml
  tests/test_files/invalid.malformed.scanner.error.yaml
  tests/test_identify.py
  tests/test_validate.py
Labels: lgtm, size/L

#36 Adding UI validation functions for operatorhub.io
  Pipfile
  operatorcourier/api.py
  operatorcourier/cli.py
  operatorcourier/const_io.py
  operatorcourier/validate.py
  setup.py
  tests/test_files/bundles/verification/valid.bundle.yaml
  tests/test_validate.py
Labels: lgtm, size/L

#42 Update version to 1.1.0
  setup.py
Labels: lgtm, size/XS

#45 Fix typo in CLI comment
  operatorcourier/cli.py
Labels: lgtm, size/XS

#40 Set up tox
  README.md
  docs/contributing.md
  operatorcourier/api.py
  operatorcourier/build.py
  operatorcourier/cli.py
  operatorcourier/const_io.py
  operatorcourier/format.py
  operatorcourier/identify.py
  operatorcourier/nest.py
  operatorcourier/push.py
  operatorcourier/validate.py
  setup.py
  tests/test_api.py
  tests/test_build.py
  tests/test_files/bundles/verification/no-data-key.bundle.yaml
  tests/test_identify.py
  tests/test_nest.py
  tests/test_validate.py
  tox.ini
Labels: lgtm, needs-ok-to-test, size/XL

#44 Add --version (-v) argument to CLI
  operatorcourier/cli.py
Labels: lgtm, size/XS

#43 Update deploy command in Makefile
  Makefile
Labels: lgtm, size/XS

#27 Add option to print validation errors and warnings to file
  .vscode/settings.json
  operatorcourier/api.py
  operatorcourier/cli.py
  operatorcourier/validate.py
  tests/test_validate.py
Labels: lgtm, size/L

#47 Raise exception for validate
  operatorcourier/api.py
Labels: lgtm, size/S

#50 Set up Travis CI and Coveralls
  .travis.yml
  operatorcourier/api.py
  operatorcourier/cli.py
Labels: lgtm, needs-ok-to-test, size/S

#53 Remove vscode settings folder
  .vscode/settings.json
Labels: lgtm, size/XS

#54 Fix push validation
  operatorcourier/api.py
Labels: lgtm, size/XS

#60 Move logging.basicConfig() from api to cli
  operatorcourier/api.py
  operatorcourier/cli.py
Labels: lgtm, size/XS

#52 Update README with build and coverage status badges
  README.md
Labels: lgtm, needs-ok-to-test, size/XS

#62 Update README about minimum supported version of Python
  README.md
  setup.py
Labels: lgtm, size/XS

#55 Remove unused "regex" module dependency
  Pipfile
  setup.py
Labels: lgtm, size/XS

#57 Update api method docs
  operatorcourier/api.py
Labels: lgtm, size/XS

#59 Update .gitignore to ignore VS Code and IntelliJ settings folder
  .gitignore
Labels: lgtm, size/XS

#61 Add tox installation as prereq in contributing doc
  docs/contributing.md
Labels: lgtm, size/XS

#67 Fix: UI capabilities validation
  operatorcourier/validate.py
Labels: lgtm, size/XS

#49 Verify packageName in bundle matches repository name
  operatorcourier/api.py
  operatorcourier/validate.py
  tests/test_files/bundles/verification/multiplepkgs.invalid.bundle.yaml
  tests/test_validate.py
Labels: size/L

#63 Clean up additional folders generated by tox
  Makefile
Labels: lgtm, size/XS

#70 Update Travis CI config to test courier on macOS
  .travis.yml
Labels: lgtm, size/S

#66 Error reporting
  operatorcourier/api.py
  operatorcourier/errors.py
  operatorcourier/identify.py
  operatorcourier/push.py
  tests/test_api.py
  tests/test_errors.py
  tests/test_identify.py
Labels: needs-ok-to-test, size/L

#78 Adding categories check
  operatorcourier/validate.py
  tests/test_files/bundles/verification/multiplepkgs.invalid.bundle.yaml
  tests/test_files/bundles/verification/nocrd.valid.bundle.yaml
  tests/test_files/bundles/verification/noicon.valid.bundle.yaml
  tests/test_files/bundles/verification/nopkg.invalid.bundle.yaml
  tests/test_files/bundles/verification/ui.invalid.bundle.yaml
  tests/test_files/bundles/verification/valid.bundle.yaml
  tests/test_validate.py
Labels: lgtm, size/M

#81 Add basic integration tests
  tests/integration/test_verify.py
  tests/test_files/yaml_source_dir/invalid_yamls_multiple_packages/dynatrace-monitoring.v0.2.0.clusterserviceversion.yaml
  tests/test_files/yaml_source_dir/invalid_yamls_multiple_packages/dynatrace.crd.yaml
  tests/test_files/yaml_source_dir/invalid_yamls_multiple_packages/dynatrace.package.yaml
  tests/test_files/yaml_source_dir/invalid_yamls_multiple_packages/dynatrace.package2.yaml
  tests/test_files/yaml_source_dir/invalid_yamls_without_package/dynatrace-monitoring.v0.2.0.clusterserviceversion.yaml
  tests/test_files/yaml_source_dir/invalid_yamls_without_package/dynatrace.crd.yaml
  tests/test_files/yaml_source_dir/valid_yamls_with_multiple_crds/crd.yaml
  tests/test_files/yaml_source_dir/valid_yamls_with_multiple_crds/crd2.yaml
  tests/test_files/yaml_source_dir/valid_yamls_with_multiple_crds/csv.yaml
  tests/test_files/yaml_source_dir/valid_yamls_with_multiple_crds/package.yaml
  tests/test_files/yaml_source_dir/valid_yamls_with_single_crd/dynatrace-monitoring.v0.2.0.clusterserviceversion.yaml
  tests/test_files/yaml_source_dir/valid_yamls_with_single_crd/dynatrace.crd.yaml
  tests/test_files/yaml_source_dir/valid_yamls_with_single_crd/dynatrace.package.yaml
  tests/test_files/yaml_source_dir/valid_yamls_without_crds/svcat.package.yaml
  tests/test_files/yaml_source_dir/valid_yamls_without_crds/svcat.v0.1.34.clusterserviceversion.yaml
Labels: lgtm, size/XXL

#87 Update version to 1.2.1
  setup.py
Labels: lgtm, size/XS

#41 Check presence and match of fields in CRD and CSV in bundle
  operatorcourier/validate.py
  tests/test_files/bundles/verification/crdmissingkindfield.invalid.bundle.yaml
  tests/test_files/bundles/verification/crdmissingpluralfield.invalid.bundle.yaml
  tests/test_files/bundles/verification/crdmissingversionfield.invalid.bundle.yaml
  tests/test_files/bundles/verification/csvcrdfieldmismatch1.invalid.bundle.yaml
  tests/test_files/bundles/verification/csvcrdfieldmismatch2.invalid.bundle.yaml
  tests/test_files/bundles/verification/csvcrdfieldmismatch3.invalid.bundle.yaml
  tests/test_files/bundles/verification/csvmissingkindfield.invalid.bundle.yaml
  tests/test_files/bundles/verification/csvmissingnamefield.invalid.bundle.yaml
  tests/test_files/bundles/verification/csvmissingversionfield.invalid.bundle.yaml
  tests/test_validate.py
Labels: lgtm, size/XXL

#68 Fix: Expand regular expression for version
  Pipfile
  Pipfile.lock
  operatorcourier/validate.py
  setup.py
  tests/test_validate.py
Labels: lgtm, size/M
