Repository operator-framework/operator-courier, pull requests merged in 2019-02, with the labels that each got.

#6 Add real build method
  Pipfile
  Pipfile.lock
  command/build.py
  command/cli.py
  command/identify.py
  tests/test_build.py
  tests/test_identify.py
Labels: size/L

#7 Add validate method
  command/validate.py
  tests/test_files/bundles/verification/invalid.bundle.yaml
  tests/test_files/bundles/verification/nocrd.valid.bundle.yaml
  tests/test_files/bundles/verification/valid.bundle.yaml
  tests/test_files/crd2.yaml
  tests/test_files/csv.yaml
  tests/test_validate.py
Labels: lgtm, size/XXL

#5 Generate and export API
  README.md
  command/cli.py
  operatorcourier/__init__.py
  operatorcourier/api.py
  operatorcourier/build.py
  operatorcourier/cli.py
  operatorcourier/identify.py
  operatorcourier/push.py
  operatorcourier/validate.py
  setup.py
  tests/test_api.py
  tests/test_build.py
  tests/test_files/bundles/api/bundle1/crd.yml
  tests/test_files/bundles/api/bundle1/csv.yaml
  tests/test_files/bundles/api/bundle1/packages.yaml
  tests/test_files/bundles/api/bundle1/results/bundle.yaml
  tests/test_identify.py
  tests/test_validate.py
Labels: size/XL

#8 Add license
  LICENSE
Labels: lgtm, size/L

#9 Fix error log messages in validator
  operatorcourier/validate.py
Labels: lgtm, size/XS

#10 Pyyaml security vulerability fix
  operatorcourier/identify.py
  tests/test_api.py
Labels: lgtm, size/XS

#11 Update package info
  setup.py
Labels: size/XS

#12 Update courier to push correctly formatted bundle
  operatorcourier/api.py
  operatorcourier/format.py
  tests/test_api.py
  tests/test_files/bundles/api/bundle1/results/bundle.yaml
  tests/test_files/bundles/verification/invalid.bundle.yaml
  tests/test_files/bundles/verification/nocrd.valid.bundle.yaml
  tests/test_files/bundles/verification/valid.bundle.yaml
  tests/test_validate.py
Labels: size/XXL

#18 Increment the version number
  setup.py
Labels: size/XS

#19 Add logging level and module name to logs
  operatorcourier/api.py
Labels: lgtm, size/XS

#22 Update README.md with example
  README.md
Labels: lgtm, size/M

#21 Pass error msg from quay.io to user
  operatorcourier/push.py
Labels: lgtm, size/S

#26 Update README with Auth info
  README.md
Labels: lgtm, size/S

#28 Add Nest Command
  operatorcourier/api.py
  operatorcourier/cli.py
  operatorcourier/nest.py
  tests/test_files/bundles/nest/bundle1/alertmanager.crd.yaml
  tests/test_files/bundles/nest/bundle1/prometheus.crd.yaml
  tests/test_files/bundles/nest/bundle1/prometheus.package.yaml
  tests/test_files/bundles/nest/bundle1/prometheusoperator.0.14.0.clusterserviceversion.yaml
  tests/test_files/bundles/nest/bundle1/prometheusoperator.0.15.0.clusterserviceversion.yaml
  tests/test_files/bundles/nest/bundle1/prometheusoperator.0.22.2.clusterserviceversion.yaml
  tests/test_files/bundles/nest/bundle1/prometheusrule.crd.yaml
  tests/test_files/bundles/nest/bundle1/servicemonitor.crd.yaml
  tests/test_files/bundles/nest/bundle1result/0.14.0/alertmanagers.monitoring.coreos.com.crd.yaml
  tests/test_files/bundles/nest/bundle1result/0.14.0/prometheuses.monitoring.coreos.com.crd.yaml
  tests/test_files/bundles/nest/bundle1result/0.14.0/prometheusoperator.0.14.0.clusterserviceversion.yaml
  tests/test_files/bundles/nest/bundle1result/0.14.0/servicemonitors.monitoring.coreos.com.crd.yaml
  tests/test_files/bundles/nest/bundle1result/0.15.0/alertmanagers.monitoring.coreos.com.crd.yaml
  tests/test_files/bundles/nest/bundle1result/0.15.0/prometheuses.monitoring.coreos.com.crd.yaml
  tests/test_files/bundles/nest/bundle1result/0.15.0/prometheusoperator.0.15.0.clusterserviceversion.yaml
  tests/test_files/bundles/nest/bundle1result/0.15.0/servicemonitors.monitoring.coreos.com.crd.yaml
  tests/test_files/bundles/nest/bundle1result/0.22.2/alertmanagers.monitoring.coreos.com.crd.yaml
  tests/test_files/bundles/nest/bundle1result/0.22.2/prometheuses.monitoring.coreos.com.crd.yaml
  tests/test_files/bundles/nest/bundle1result/0.22.2/prometheusoperator.0.22.2.clusterserviceversion.yaml
  tests/test_files/bundles/nest/bundle1result/0.22.2/prometheusrules.monitoring.coreos.com.crd.yaml
  tests/test_files/bundles/nest/bundle1result/0.22.2/servicemonitors.monitoring.coreos.com.crd.yaml
  tests/test_files/bundles/nest/bundle1result/prometheus.package.yaml
  tests/test_nest.py
Labels: lgtm, size/XXL

#31 [Docs] Update example push command in README
  README.md
Labels: lgtm, size/XS
