Repository operator-framework/operator-courier, pull requests merged in 2019-04, with the labels that each got.

#90 Update version to 1.3.0
  setup.py
Labels: lgtm, size/XS

#92 Fix raising exception in flatten api
  operatorcourier/flatten.py
Labels: lgtm, size/XS

#80 Use argparse subparsers for subcommands
  operatorcourier/cli.py
Labels: lgtm, needs-ok-to-test, size/L

#89 CLI: Add --verbose mode option
  operatorcourier/cli.py
Labels: lgtm, size/S

#97 Explicitly handle an error case.
  operatorcourier/flatten.py
Labels: lgtm, size/XS

#94 CliParser: Print help when no argument is passed
  operatorcourier/cli.py
Labels: lgtm, needs-ok-to-test, size/XS

#93 flatten: copy files to dest_dir when structure is already flat
  operatorcourier/flatten.py
  tests/test_flatten.py
Labels: lgtm, size/S

#98 use OS specific path separator
  operatorcourier/api.py
  operatorcourier/nest.py
  operatorcourier/push.py
  operatorcourier/validate.py
Labels: lgtm, ok-to-test, size/S

#105 Revert "Add Optional Output File"
  operatorcourier/api.py
  operatorcourier/cli.py
  tests/integration/test_verify.py
Labels: lgtm, size/M

#108 Adding Developer Tools Category
  operatorcourier/validate.py
Labels: lgtm, size/XS

#103 validate: add validations for csv spec.install
  operatorcourier/validate.py
  tests/test_files/bundles/verification/csvinstallspecnotlists.invalid.bundle.yaml
  tests/test_files/bundles/verification/csvinstallstrategywrongvalue.invalid.bundle.yaml
  tests/test_files/bundles/verification/csvmissinginstallattributes.invalid.bundle.yaml
  tests/test_files/bundles/verification/valid.bundle.yaml
  tests/test_validate.py
Labels: lgtm, ok-to-test, size/XL

#82 Update tox for integration tests and add tests for push
  docs/contributing.md
  run_integration_tests.sh
  tests/integration/test_push.py
  tox.ini
Labels: size/L

#102 Support nested directory layout
  operatorcourier/api.py
  operatorcourier/validate.py
  operatorcourier/verified_manifest.py
  tests/test_api.py
  tests/test_files/bundles/api/etcd_invalid_nested_bundle/0.6.1/etcdcluster.crd.yaml
  tests/test_files/bundles/api/etcd_invalid_nested_bundle/0.6.1/etcdoperator.clusterserviceversion.yaml
  tests/test_files/bundles/api/etcd_invalid_nested_bundle/0.9.0/etcdbackup.crd.yaml
  tests/test_files/bundles/api/etcd_invalid_nested_bundle/0.9.0/etcdcluster.crd.yaml
  tests/test_files/bundles/api/etcd_invalid_nested_bundle/0.9.0/etcdoperator.v0.9.0.clusterserviceversion.yaml
  tests/test_files/bundles/api/etcd_invalid_nested_bundle/0.9.0/etcdrestore.crd.yaml
  tests/test_files/bundles/api/etcd_invalid_nested_bundle/0.9.2/etcdbackup.crd.yaml
  tests/test_files/bundles/api/etcd_invalid_nested_bundle/0.9.2/etcdcluster.crd.yaml
  tests/test_files/bundles/api/etcd_invalid_nested_bundle/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml
  tests/test_files/bundles/api/etcd_invalid_nested_bundle/0.9.2/etcdrestore.crd.yaml
  tests/test_files/bundles/api/etcd_invalid_nested_bundle/etcd.package.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.6.1/etcdcluster.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.6.1/etcdoperator.clusterserviceversion.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.9.0/etcdbackup.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.9.0/etcdcluster.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.9.0/etcdoperator.v0.9.0.clusterserviceversion.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.9.0/etcdrestore.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.9.2/etcdbackup.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.9.2/etcdcluster.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.9.2/etcdrestore.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/etcd.package.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle/0.14.0/alertmanager.crd.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle/0.14.0/prometheus.crd.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle/0.14.0/prometheusoperator.0.14.0.clusterserviceversion.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle/0.14.0/prometheusrule.crd.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle/0.14.0/servicemonitor.crd.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle/0.15.0/alertmanager.crd.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle/0.15.0/prometheus.crd.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle/0.15.0/prometheusoperator.0.15.0.clusterserviceversion.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle/0.15.0/prometheusrule.crd.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle/0.15.0/servicemonitor.crd.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle/0.22.2/alertmanager.crd.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle/0.22.2/prometheus.crd.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle/0.22.2/prometheusoperator.0.22.2.clusterserviceversion.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle/0.22.2/prometheusrule.crd.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle/0.22.2/servicemonitor.crd.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle/prometheus.package.yaml
Labels: lgtm, size/XXL

#111 nest: Fix error for operators without CRDs
  operatorcourier/nest.py
  tests/test_files/bundles/nest/bundle2/svcat.package.yaml
  tests/test_files/bundles/nest/bundle2/svcat.v0.1.34.clusterserviceversion.yaml
  tests/test_files/bundles/nest/bundle2result/0.1.34/svcat.v0.1.34.clusterserviceversion.yaml
  tests/test_files/bundles/nest/bundle2result/svcat.package.yaml
  tests/test_nest.py
Labels: lgtm, size/XXL

#110 Catch correct error for invalid json in alm-examples
  operatorcourier/validate.py
Labels: lgtm, size/XS

#113 Raise error after validation is written to file
  operatorcourier/api.py
  operatorcourier/verified_manifest.py
  tests/integration/test_verify.py
  tests/test_api.py
Labels: lgtm, size/L

#114 Update version to 2.0.0
  setup.py
Labels: size/XS

#115 Update README about directory structure and validation errors
  README.md
Labels: lgtm, size/M

#116 Remove SemVer requirement on nested folders
  operatorcourier/verified_manifest.py
  tests/test_api.py
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.6/etcdcluster.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.6/etcdoperator.clusterserviceversion.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.8/etcdbackup.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.8/etcdcluster.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.8/etcdoperator.v0.9.0.clusterserviceversion.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.8/etcdrestore.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.9/etcdbackup.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.9/etcdcluster.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.9/etcdoperator.v0.9.2.clusterserviceversion.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle/0.9/etcdrestore.crd.yaml
  tests/test_files/bundles/api/results/bundle.yaml
Labels: lgtm, size/S

#117 Update version to 2.0.1
  setup.py
Labels: lgtm, size/XS

#118 Remove SemVer requirement for nested version folders for flatten command
  operatorcourier/flatten.py
  tests/test_files/bundles/flatten/etcd_valid_input_3/0.61/etcdbackup.crd.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_3/0.61/etcdcluster.crd.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_3/0.61/etcdoperator.clusterserviceversion.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_3/0.61/etcdrestore.crd.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_3/0.90/etcdbackup.crd.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_3/0.90/etcdcluster.crd.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_3/0.90/etcdoperator.v0.9.0.clusterserviceversion.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_3/0.90/etcdrestore.crd.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_3/0.92/etcdbackup.crd.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_3/0.92/etcdcluster.crd.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_3/0.92/etcdoperator.v0.9.2.clusterserviceversion.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_3/0.92/etcdrestore.crd.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_3/random_folder/random_file.txt
  tests/test_flatten.py
Labels: size/M
