Repository operator-framework/operator-courier, pull requests merged in 2019-05, with the labels that each got.

#122 Only parse manifest folders with valid bundle files
  operatorcourier/flatten.py
  operatorcourier/manifest_parser.py
  operatorcourier/verified_manifest.py
  tests/integration/test_push.py
  tests/integration/test_verify.py
  tests/test_api.py
  tests/test_files/bundles/api/etcd_valid_nested_bundle_with_random_folder/etcd.package.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle_with_random_folder/random_folder/package.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle_with_random_folder/random_folder/random_file.txt
  tests/test_files/bundles/api/etcd_valid_nested_bundle_with_random_folder/version_0.6/etcdcluster.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle_with_random_folder/version_0.6/etcdoperator.clusterserviceversion.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle_with_random_folder/version_0.8/etcdbackup.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle_with_random_folder/version_0.8/etcdcluster.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle_with_random_folder/version_0.8/etcdoperator.v0.9.0.clusterserviceversion.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle_with_random_folder/version_0.8/etcdrestore.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle_with_random_folder/version_0.9/etcdbackup.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle_with_random_folder/version_0.9/etcdcluster.crd.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle_with_random_folder/version_0.9/etcdoperator.v0.9.2.clusterserviceversion.yaml
  tests/test_files/bundles/api/etcd_valid_nested_bundle_with_random_folder/version_0.9/etcdrestore.crd.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle_2/0.14.0/alertmanager.crd.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle_2/0.14.0/prometheus.crd.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle_2/0.14.0/prometheusoperator.0.14.0.clusterserviceversion.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle_2/0.14.0/prometheusrule.crd.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle_2/0.14.0/servicemonitor.crd.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle_2/prometheus.package.yaml
  tests/test_files/bundles/api/prometheus_valid_nested_bundle_2/prometheusoperator.0.14.0.clusterserviceversion.yaml
  tests/test_files/bundles/api/valid_flat_bundle/crd.yml
  tests/test_files/bundles/api/valid_flat_bundle/csv.yaml
  tests/test_files/bundles/api/valid_flat_bundle/packages.yaml
  tests/test_files/bundles/api/valid_flat_bundle_with_random_folder/crd.yml
  tests/test_files/bundles/api/valid_flat_bundle_with_random_folder/csv.yaml
  tests/test_files/bundles/api/valid_flat_bundle_with_random_folder/packages.yaml
  tests/test_files/bundles/api/valid_flat_bundle_with_random_folder/random_folder/package.yaml
  tests/test_files/bundles/api/valid_flat_bundle_with_random_folder/random_folder/random_file.txt
  tests/test_files/bundles/flatten/etcd_valid_input_5/random_folder1/package.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_5/random_folder1/random_file.txt
  tests/test_files/bundles/flatten/etcd_valid_input_5/random_folder2/random_file.txt
  tests/test_files/bundles/flatten/etcd_valid_input_6/0.9/etcdbackup.crd.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_6/0.9/etcdcluster.crd.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_6/0.9/etcdoperator.clusterserviceversion.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_6/0.9/etcdrestore.crd.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_6/etcd.package.yaml
  tests/test_files/bundles/flatten/etcd_valid_input_6/etcdoperator.clusterserviceversion.yaml
  tests/test_files/yaml_source_dir/invalid_yamls_multiple_packages/dynatrace.package2.yaml
  tests/test_flatten.py
Labels: size/XXL

#123 Remove logging for identify
  operatorcourier/identify.py
Labels: lgtm, size/XS

#126 Update OWNERS file reviewers
  OWNERS
Labels: size/XS

#129 Use os.path.relpath to calculate relative paths
  operatorcourier/nest.py
  tests/test_nest.py
Labels: lgtm, size/XS

#130 Update version to 2.0.3
  setup.py
Labels: size/XS

#131 Update README about installation and upgrade
  README.md
Labels: lgtm, size/S

#132 Add "Application Runtime" as a valid category
  operatorcourier/validate.py
Labels: lgtm, size/XS

#121 Run in docker
  Dockerfile
  README.md
Labels: lgtm, size/S

#133 Add filename to warnings and errors
  operatorcourier/build.py
  operatorcourier/validate.py
  operatorcourier/verified_manifest.py
  tests/test_build.py
  tests/test_validate.py
Labels: size/L

#134 Update version to 2.1.0
  setup.py
Labels: size/XS
